extern const GeoLayout jambi_skyboxes_Switch_opt1[];
extern const GeoLayout jambi_skyboxes_Switch_opt2[];
extern const GeoLayout jambi_skyboxes_Switch_opt3[];
extern const GeoLayout jambi_skyboxes_Switch_opt4[];
extern const GeoLayout jambi_skyboxes_Switch_opt5[];
extern const GeoLayout jambi_skyboxes_Switch_opt6[];
extern const GeoLayout jambi_skyboxes_Switch_opt7[];
extern const GeoLayout jambi_skyboxes_Switch_opt8[];
extern const GeoLayout jambi_skyboxes_Switch_opt9[];
extern const GeoLayout jambi_skyboxes_Switch_opt10[];
extern const GeoLayout jambi_skyboxes_Switch_opt11[];
extern const GeoLayout jambi_skyboxes_Switch_opt12[];
extern const GeoLayout jambi_skyboxes_Switch_opt13[];
extern const GeoLayout jambi_skyboxes_Switch_opt14[];
extern const GeoLayout jambi_skyboxes_Switch_opt15[];
extern const GeoLayout jambi_skyboxes_geo[];
extern u8 jambi_skyboxes_Ocean_rgba16[];
extern u8 jambi_skyboxes_Sunset_rgba16[];
extern u8 jambi_skyboxes_Hell_rgba16[];
extern u8 jambi_skyboxes_EvilSky_rgba16[];
extern u8 jambi_skyboxes_Clouds_rgba16[];
extern u8 jambi_skyboxes_Snow_rgba16[];
extern u8 jambi_skyboxes_Spooky_rgba16[];
extern u8 jambi_skyboxes_NightSnow_rgba16[];
extern u8 jambi_skyboxes_Desert_rgba16[];
extern u8 jambi_skyboxes_Gloomy_rgba16[];
extern u8 jambi_skyboxes_DarkWorld_rgba16[];
extern u8 jambi_skyboxes_UnderwaterCity_rgba16[];
extern u8 jambi_skyboxes_Swamp_rgba16[];
extern u8 jambi_skyboxes_Night_rgba16[];
extern u8 jambi_skyboxes_Space_rgba16[];
extern u8 jambi_skyboxes_SpaceRed_rgba16[];
extern Vtx jambi_skyboxes_Skybox_DL_mesh_layer_0_vtx_0[234];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_tri_0[];
extern Gfx mat_jambi_skyboxes__0_Ocean[];
extern Gfx mat_revert_jambi_skyboxes__0_Ocean[];
extern Gfx mat_jambi_skyboxes__1_Sunset[];
extern Gfx mat_revert_jambi_skyboxes__1_Sunset[];
extern Gfx mat_jambi_skyboxes__2_Hell[];
extern Gfx mat_revert_jambi_skyboxes__2_Hell[];
extern Gfx mat_jambi_skyboxes__3_Evil[];
extern Gfx mat_revert_jambi_skyboxes__3_Evil[];
extern Gfx mat_jambi_skyboxes__4_Clouds[];
extern Gfx mat_revert_jambi_skyboxes__4_Clouds[];
extern Gfx mat_jambi_skyboxes__5_Winter[];
extern Gfx mat_revert_jambi_skyboxes__5_Winter[];
extern Gfx mat_jambi_skyboxes__6_Spooky[];
extern Gfx mat_revert_jambi_skyboxes__6_Spooky[];
extern Gfx mat_jambi_skyboxes__7_Night[];
extern Gfx mat_revert_jambi_skyboxes__7_Night[];
extern Gfx mat_jambi_skyboxes__8_Desert[];
extern Gfx mat_revert_jambi_skyboxes__8_Desert[];
extern Gfx mat_jambi_skyboxes__9_Gloomy[];
extern Gfx mat_revert_jambi_skyboxes__9_Gloomy[];
extern Gfx mat_jambi_skyboxes__10_Darkworld[];
extern Gfx mat_revert_jambi_skyboxes__10_Darkworld[];
extern Gfx mat_jambi_skyboxes__11_Underwater[];
extern Gfx mat_revert_jambi_skyboxes__11_Underwater[];
extern Gfx mat_jambi_skyboxes__12_Swamp[];
extern Gfx mat_revert_jambi_skyboxes__12_Swamp[];
extern Gfx mat_jambi_skyboxes__13_Night[];
extern Gfx mat_revert_jambi_skyboxes__13_Night[];
extern Gfx mat_jambi_skyboxes__14_Space[];
extern Gfx mat_revert_jambi_skyboxes__14_Space[];
extern Gfx mat_jambi_skyboxes__15_Space_Red[];
extern Gfx mat_revert_jambi_skyboxes__15_Space_Red[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__1_Sunset_0[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__2_Hell_1[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__3_Evil_2[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__4_Clouds_3[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__5_Winter_4[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__6_Spooky_5[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__7_Night_6[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__8_Desert_7[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__9_Gloomy_8[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__10_Darkworld_9[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__11_Underwater_10[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__12_Swamp_11[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__13_Night_12[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__14_Space_13[];
extern Gfx jambi_skyboxes_Skybox_DL_mesh_layer_0_mat_override__15_Space_Red_14[];
